name: "Dependabot auto-merge"
description: "Approves and merges Dependabot PRs"


inputs:
  github_token:
    description: "GitHub token used for commenting on and approving PR"
    required: true

runs:
  using: "composite"
  steps:
      - name: approve-and-request-merge
        uses: actions/github-script@v4.0.2
        with:
          script: |
            const opts = github.pulls.listReviews.endpoint.merge({
              pull_number: context.payload.pull_request.number,
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
            });

            const comments = await github.paginate(opts);

            const mergeComment = comments.find(
              (review) =>
                review.body === "@dependabot merge" && review.state === "APPROVED"
            );

            if (mergeComment) {
              console.log(
                `The user "${mergeComment.user.login}" has already approved and requested this PR is merged, exiting`
              );
              return;
            }

            github.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: '@dependabot merge'
            })
          github-token: ${{ inputs.github_token }}